In [1]:
import numpy as np
import matplotlib.pyplot as plt
%matplotlib notebook
from sklearn.gaussian_process import GaussianProcessRegressor
import pandas as pd

In [ ]:
X = np.load('initial_data/function_7/initial_inputs.npy')
Y = np.load('initial_data/function_7/initial_outputs.npy')

In [7]:
my_dict = {
    'X1': X[:,0],
    'X2': X[:,1],
    'X3': X[:,2],
    'X4': X[:,3],
    'X5': X[:,4],
    'X6': X[:,5],
    'Y' : Y
}

df = pd.DataFrame(my_dict)
df

X1        X2        X3        X4        X5        X6         Y
0   0.272624  0.324495  0.897109  0.832951  0.154063  0.795864  0.604433
1   0.543003  0.924694  0.341567  0.646486  0.718440  0.343133  0.562753
2   0.090832  0.661529  0.065931  0.258577  0.963453  0.640265  0.007503
3   0.118867  0.615055  0.905816  0.855300  0.413631  0.585236  0.061424
4   0.630218  0.838097  0.680013  0.731895  0.526737  0.348429  0.273047
5   0.764919  0.255883  0.609084  0.218079  0.322943  0.095794  0.083747
6   0.057896  0.491672  0.247422  0.218118  0.420428  0.730970  1.364968
7   0.195252  0.079227  0.554580  0.170567  0.014944  0.107032  0.092645
8   0.642303  0.836875  0.021793  0.101488  0.683071  0.692416  0.017870
9   0.789943  0.195545  0.575623  0.073659  0.259049  0.051100  0.033565
10  0.528497  0.457424  0.360096  0.362046  0.816891  0.637476  0.073516
11  0.722615  0.011813  0.063646  0.165173  0.079244  0.359952  0.206310
12  0.075665  0.334502  0.132733  0.608312  0.918386  0.822331  0.008826
13  0.942451  0.377440  0.486122  0.228791  0.082632  0.711958  0.268400
14  0.148647  0.033943  0.728806  0.316066  0.021769  0.516918  0.611526
15  0.817112  0.548168  0.103348  0.124370  0.728235  0.449674  0.014798
16  0.417626  0.064100  0.245669  0.559041  0.191531  0.254641  0.274893
17  0.726286  0.464896  0.924571  0.807245  0.635438  0.143418  0.066763
18  0.319810  0.520098  0.290678  0.876707  0.495035  0.619082  0.042118
19  0.879871  0.397962  0.003635  0.956991  0.264514  0.114869  0.002701
20  0.541241  0.631403  0.031902  0.449982  0.798653  0.633704  0.018209
21  0.226348  0.115026  0.824750  0.945384  0.905312  0.951014  0.007016
22  0.686853  0.041017  0.007573  0.285009  0.691568  0.655543  0.100507
23  0.175978  0.624416  0.295542  0.469553  0.097770  0.728141  0.475396
24  0.881647  0.204450  0.414474  0.420385  0.264915  0.730660  0.675142
25  0.066611  0.528045  0.816095  0.961017  0.086509  0.777788  0.516457
26  0.932466  0.488812  0.258608  0.956243  0.190428  0.519852  0.003777
27  0.846867  0.142429  0.060669  0.756292  0.552398  0.081306  0.003134
28  0.806282  0.324122  0.726076  0.148712  0.719376  0.362884  0.021343
29  0.476823  0.340942  0.014335  0.880140  0.998655  0.079664  0.095411

In [8]:
gpr = GaussianProcessRegressor()
gpr.fit(X, Y)

# to optimize the acquisition function, we will simply use gridsearch
x1 = np.linspace(0, 1, 15)
x2 = np.linspace(0, 1, 15)
x3 = np.linspace(0, 1, 15)
x4 = np.linspace(0, 1, 15)
x5 = np.linspace(0, 1, 15)
x6 = np.linspace(0, 1, 15)

X_grid = []
for i in range(len(x1)):
    for j in range(len(x2)):
        for k in range(len(x3)):
            for l in range(len(x4)):
                for m in range(len(x5)):
                    for n in range(len(x6)):
                        X_grid.append([x1[i], x2[j], x3[k], x4[l], x5[m], x6[n]])

X_grid = np.array(X_grid)
mean, std = gpr.predict(X_grid, return_std = True)
ucb = mean + 1.96 * std

idx_max = np.argmax(ucb)
next_query = X_grid[idx_max]
print(str(round(next_query[0],6)) + '-' + str(round(next_query[1],6)) + '-' + str(round(next_query[2],6)) + '-' + str(round(next_query[3],6)) + '-' + str(round(next_query[4],6)) + '-' + str(round(next_query[5],6)))

[[0.         0.         0.         0.         0.         0.        ]
 [0.         0.         0.         0.         0.         0.07142857]
 [0.         0.         0.         0.         0.         0.14285714]
 ...
 [1.         1.         1.         1.         1.         0.85714286]
 [1.         1.         1.         1.         1.         0.92857143]
 [1.         1.         1.         1.         1.         1.        ]]
0.0-0.0-0.071429-0.0-0.142857-1.0
